# Generated by Django 4.0.5 on 2022-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwwwardsClone', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
